version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seguranca-web_app
    ports:
      - 8080:80
      - 443:443
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./tls/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./tls/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./tls/MyCertificate.crt:/etc/ssl/certs/MyCertificate.crt
      - ./tls/server.key:/etc/ssl/private/server.key
    env_file:
      - path: ./.env/mysql.dev.env
        required: false # development
      - path: /mnt/seguranca_web/secrets/prod.env
        required: false # production, for Linux. Created by running `./compose-production.sh`. Overrides the development env file.
    depends_on:
      - mysql

  mysql:
    image: mysql:9.0
    container_name: seguranca-web_mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    env_file:
      - path: ./.env/mysql.dev.env
        required: false # development
      - path: /mnt/seguranca_web/secrets/prod.env
        required: false # production, for Linux. Created by running `./compose-production.sh`. Overrides the development env file.
