version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seguranca-web_app
    ports:
      - 8080:80
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    env_file:
      - path: ./dev.env
        required: false # development, overrides the production env file
      - path: /mnt/seguranca_web/secrets/prod.env
        required: false # production, for Linux. Created by running `./compose-production.sh`. Overrides the development env file.
    depends_on:
      - mysql

  mysql:
    image: mysql:9.0
    container_name: seguranca-web_mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    env_file:
      - path: ./dev.env
        required: false # development
      - path: /mnt/seguranca_web/secrets/prod.env
        required: false # production, for Linux. Created by running `./compose-production.sh`. Overrides the development env file.
