version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seguranca-web_app
    ports:
      - 8080:80
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:9.0
    container_name: seguranca-web_mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
